Create readme file
eoscostarica/lacchain-eosio-scripts pull request #6
Opened 2021-07-12 16:03 UTC by AngeloCG97

### Create readme file.

2021-07-12 16:35 UTC, xavier506 commented
@AngeloCG97 

- Is the LAC Chain Logo showing?

- Lets adjust the file structure and add description texts to missing files / folders 

![image](https://user-images.githubusercontent.com/5632966/125323902-8f5ffa80-e2fc-11eb-92db-38e21ac101ae.png)

- EOS Costa Rica Logo is not centered

2021-07-12 18:46 UTC, leisterfrancisco requested changes

2021-07-12 18:46 UTC, leisterfrancisco commented on README.md
> +```
What if we make it like this:
```
/
├── deployContract
│   └── holacontrato.cpp ..................... Se muestra el contrato holacontrato que se encuentra en la red https://lacchain.eosio.online/accounts
│   └── holacontrato.sh ...................... Se muestra cómo compilar para el contrato holacontrato
├── prepareTransaction
│   └── eosJS
│       └── holacontrato.js .................. Se muestra cómo preparar una transacción para el contrato holacontrato por medio de eosJS
│       └── transacction.js .................. Se muestra cómo preparar una transacción por medio de eosJS
│	└── shellScript
│		└── holacontrato.sh .......... Se muestra cómo preparar una transacción para el contrato holacontrato por medio de sh
├── LICENSE .................................. Términos y Condiciones
└── README.md ................................ Especificación del repositorio
```

2021-07-12 20:54 UTC, xavier506 commented on README.md
> +## Lacchain-scripts
maybe we dont need this header

2021-07-13 01:24 UTC, xavier506 approved these changes
LGTM

2021-07-13 01:24 UTC, merged